---
- hosts: all
  become: yes
  become_user: root
  environment:
    http_proxy: "{{ http_proxy | default() }}"
    https_proxy: "{{ https_proxy | default() }}"
    no_proxy: "{{ no_proxy | default() }}"
  roles:
    - name: trombik.git
    - name: trombik.openntpd
    - name: trombik.poudriere
    - name: setup
    - name: build

  vars:
    project_jails:
      - 130amd64
      - 123amd64
    project_packages:
      - devel/binutils-esp32s2ulp
      - devel/binutils-esp32ulp
      - devel/riscv32-esp-elf
      - devel/xtensa-esp32-elf
      - devel/xtensa-esp32s2-elf
      - devel/xtensa-lx106-elf
    project_make_job_numbers: 2
    project_binary_package_branch: quarterly
    project_ports_branch: 2022Q1

    # _____________________________openntpd
    openntpd_config: |
      servers pool.ntp.org
      sensor *
      constraints from "https://www.google.com"
      listen on 127.0.0.1
    # _____________________________poudriere
    project_poudriere_basefs: /usr/local/poudriere
    project_ports_dir: "{{ project_poudriere_basefs }}/ports"
    project_ports_dir_default: "{{ project_poudriere_basefs }}/ports/default"
    poudriere_package: ports-mgmt/poudriere-devel
    poudriere_make_conf_files:
      - name: make.conf
        state: present
        content: |
          LICENSES_ACCEPTED=MSPAT OSI
          MAKE_JOB_NUMBERS={{ project_make_job_numbers }}
    poudriere_config:
      BASEFS: /usr/local/poudriere
      FREEBSD_HOST: http://ftp.freebsd.org
      NO_ZFS: "yes"
      # GIT_URL: "https://github.com/reallyenglish/freebsd-ports-mini.git"
      CHECK_CHANGED_OPTIONS: verbose
      NOLINUX: "yes"
      PKG_REPO_SIGNING_KEY: /usr/local/etc/poudriere/keys/my.key
      CCACHE_DIR: /var/cache/ccache
      ALLOW_MAKE_JOBS_PACKAGES: "{{ project_packages | join(' ') }}"
      FLAVOR_DEFAULT_ALL: "yes"
      USE_TMPFS: "no"

    poudriere_ports:
      default:
        state: present
        extra_flags: -B {{ project_ports_branch }}
        path: "{{ project_ports_dir }}/default"
      xtensa_esp32_elf:
        state: present
        extra_flags: -m git+https -U https://github.com/trombik/xtensa-esp32-elf.git -B devel
        path: "{{ project_ports_dir }}/xtensa-esp32-elf"
      freebsd_ports_xtensa_lx106_elf:
        state: present
        extra_flags: -m git+https -U https://github.com/trombik/freebsd-ports-xtensa-lx106-elf.git -B master
        path: "{{ project_ports_dir }}/freebsd-ports-xtensa-lx106"

    poudriere_jails:
      130amd64:
        method: http
        version: 13.0-RELEASE
        state: present
      123amd64:
        method: http
        version: 12.3-RELEASE
        state: present
