---

- name: Dump all hostvars
  debug: var=hostvars[inventory_hostname]

- name: Install git
  ansible.builtin.pkgng:
    name: git-lite
    state: present

- name: Include encrypted variables
  ansible.builtin.include_vars:
    file: ../../secret.yml

