---
name: molecule
on:
  - pull_request
  - push
jobs:
  pre_build:

    # A job to see if the entrire jobs should be skipped.
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v3.4.1
        with:
          concurrent_skipping: same_content
          skip_after_successful_duplicate: 'true'
          paths_ignore: '["**/*.md", "**/docs/**"]'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'

  vagrant:
    needs:
      - pre_build
    # always run CI in main (or master) branch so that cache in main can be
    # reused in pull_request or push. this reduces the number of box download.
    # vagrant cloud throttles requests after many download requests.
    if: ${{ needs.pre_build.outputs.should_skip != 'true' || github.ref_name == 'main' || github.ref_name == 'master' }}
    runs-on: macos-10.15
    outputs:
      instances: ${{ steps.set-instances.outputs.instances }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Install ansible
        run: |
          pip install --user ansible

      - name: Cache vagrant boxes
        uses: actions/cache@v2
        env:
          cache-name: vagrant-boxes
        with:
          path: ~/.vagrant.d/boxes/
          key: molecule-vagrant-boxes-${{ hashFiles('**/molecule.yml') }}
          restore-keys: molecule-vagrant-boxes-${{ hashFiles('**/molecule.yml') }}

      - name: Install roles
        run: |
          .local/bin/ansible-galaxy role install -r requirements.yml

      - name: Run vagrant
        run: |
          vagrant up

  all_build:
    # a meta job that requires all of the above so that repository
    # admin can choose a single test name in "Require status checks to pass
    # before merging". A trick obtained from:
    #
    # https://github.com/jazzband/pip-tools/issues/1085#issuecomment-619172509
    name: All build
    runs-on: ubuntu-latest
    needs:
      - pre_build
      - vagrant
    steps:
      - name:
        run: |
          echo "All builds finished"
          # molecule/default/converge.yml
